-- MySQL Script generated by MySQL Workbench
-- 03/16/16 15:43:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ZoneIn_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ZoneIn_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ZoneIn_DB` DEFAULT CHARACTER SET utf8 ;
USE `ZoneIn_DB` ;

-- -----------------------------------------------------
-- Table `ZoneIn_DB`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZoneIn_DB`.`places` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `description` TEXT NOT NULL,
  `lat` DOUBLE NOT NULL,
  `long` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZoneIn_DB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZoneIn_DB`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `email` VARCHAR(500) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `lat` DOUBLE NULL DEFAULT NULL,
  `long` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `last_place_id` (`lat` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZoneIn_DB`.`follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZoneIn_DB`.`follows` (
  `follower` INT(11) NOT NULL,
  `followed` INT(11) NOT NULL,
  PRIMARY KEY (`follower`, `followed`),
  INDEX `fk_users_has_users_users1_idx` (`followed` ASC),
  INDEX `fk_users_has_users_users_idx` (`follower` ASC),
  CONSTRAINT `fk_users_has_users_users`
    FOREIGN KEY (`follower`)
    REFERENCES `ZoneIn_DB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`followed`)
    REFERENCES `ZoneIn_DB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `ZoneIn_DB`.`checkin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZoneIn_DB`.`checkin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `placeID` INT(11) NOT NULL,
  `userID` INT(11) NOT NULL,
  `likes` INT(11) NOT NULL default 0,
   PRIMARY KEY (`id`),
   CONSTRAINT `fk1`
     FOREIGN KEY (`userID`)
     REFERENCES `ZoneIn_DB`.`users` (`id`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION,
   CONSTRAINT `fk2`
     FOREIGN KEY (`placeID`)
     REFERENCES `ZoneIn_DB`.`places` (`id`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `ZoneIn_DB`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZoneIn_DB`.`comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `checkinID` INT(11) NOT NULL,
  `comment` TEXT NOT NULL,
   PRIMARY KEY (`id`),
   CONSTRAINT `fk3`
     FOREIGN KEY (`checkinID`)
     REFERENCES `ZoneIn_DB`.`checkin` (`id`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
   

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `ZoneIn_DB`.`users`
-- -----------------------------------------------------
ALTER TABLE `users` ADD `numberofnotification` INT NOT NULL AFTER `long`;

-- -----------------------------------------------------
-- Table `ZoneIn_DB`.`user_place`
-- -----------------------------------------------------
CREATE TABLE `zonein_db`.`user_place` ( `userID` INT NOT NULL , `placeID` INT NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `user_place`
  DROP PRIMARY KEY,
   ADD PRIMARY KEY(
     `userID`,
     `placeID`);
-- -----------------------------------------------------
-- Table `ZoneIn_DB`.`notification`
-- -----------------------------------------------------
CREATE TABLE `zonein_db`.`notification` ( 
`notfID` INT NOT NULL , 
`toID` INT NOT NULL , `postID` INT NOT NULL , 
`FromID` INT NOT NULL , PRIMARY KEY (`notfID`)) 
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ZoneIn_DB`.`notification`
-- -----------------------------------------------------

ALTER TABLE `notification`
ADD `seen` INT NOT NULL AFTER `FromID`, 
ADD `type` INT NOT NULL AFTER `seen`, 
ADD `txt` TEXT NOT NULL AFTER `type`;

